[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "libero"
version = "0.1.0"
description = "LIBERO: Benchmarking Knowledge Transfer for Lifelong Robot Learning"
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.12,<3.13"
authors = [
    { name = "Bo Liu", email = "bliu@cs.utexas.edu" },
    { name = "Yifeng Zhu", email = "yifengz@cs.utexas.edu" },
    { name = "Chongkai Gao" },
    { name = "Yihao Feng" },
    { name = "Qiang Liu" },
    { name = "Yuke Zhu" },
    { name = "Peter Stone" },
]

dependencies = [
    "hydra-core>=1.2.0",
    "wandb>=0.13.1",
    "transformers>=4.21.1",
    "einops==0.4.1",
    "easydict>=1.13,<2",
    "cloudpickle>=3.1.2,<4",
    "mujoco>=3.3.0,<3.10.0",
    "robosuite@git+https://github.com/ARISE-Initiative/robosuite",
    "robosuite-models>=1.0.0,<2",
    "robomimic>=0.3.0,<0.4",
    "thop>=0.1.1.0,<0.2",
    "bddl>=3.6.0,<4",
    "gymnasium>=1.3.0,<2",
    "torch",
    "torchvision",
    "egl-probe @ git+https://github.com/mmattamala/egl_probe/",
]

[project.scripts]
"libero.config_copy" = "scripts.config_copy:main"
"libero.create_template" = "scripts.create_template:main"
"libero.download_dataset" = "scripts.download_dataset:main"
"lifelong.eval" = "libero.lifelong.evaluate:main"
"lifelong.main" = "libero.lifelong.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/libero", "scripts"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pixi.workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "libero"
platforms = [{name="linux-gpu", platform = "linux-64", cuda = "13"},
             {name="linux-cpu", platform = "linux-64"},
             "osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[tool.pixi.pypi-dependencies]
libero = { path = ".", editable = true }

[tool.pixi.target.osx.dependencies]
cmake = ">=3.24.2"

[tool.pixi.environments]
gpu = { features = ["gpu"] }
default = { features = ["cpu"] }

[tool.pixi.feature.cpu]
platforms = ["linux-cpu", "osx-arm64"]

[tool.pixi.feature.gpu]
platforms = ["linux-gpu"]

[tool.pixi.feature.gpu.dependencies]
cuda-version = ">=13"

[tool.pixi.feature.gpu.pypi-dependencies]
torch = { version = "*", index = "https://download.pytorch.org/whl/cu130" }
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu130" }
torchmetrics = { version = "*", index = "https://download.pytorch.org/whl/cu130" }
